---
title: "Лабораторная работа 1 - Визуализация данных с помощью ggplot2 (функция `qplot`)"
author: "Razor_Z_Pi"
date: "2024-02-20"
output: html_document
---

### Задание 1 (Вариант - 4)

Задание 1 – С помощью функции qplot напишите программный код, строящий следующие графики по набору данных diamonds.

```{r}
library(ggplot2)

summary(diamonds)

qplot(depth, data = diamonds, color = cut, fill = cut) +
  scale_x_continuous("Depth") +
  ylab("Frequency") +
  labs( title = "Histogram of Depth by Cut")
```

### Задание 2 (Вариант - 4)

Постройте два произвольных графика, показав умение использовать различные настройки для набора данных по заданному варианту. Дайте описание набору данных и то, что показывает изображенный график.

`Вариант – 4 (CO2)`

```{r}
library(ggplot2)

qplot(x = conc, y = uptake, data=CO2, color = Type, fill = Type,
      xlim = c(110, 1000), 
      ylim = c(20, 40)) +
  geom_point(colour = "darkgreen", alpha = 0.2) +
  geom_smooth(size = 2) + 
  labs(
    title = "Поглощение диоксида углерода травянистыми растениями",
    caption = "Данные",
    x = "Концентрация CO2 в окружающей среде (мл/л)",
    y = "Скорость поглощения CO2 (ммоль/м^2 сек)",
    colour = "Origin",
    tag = "Первый",
  ) +
  geom_text(
    label = "p", 
    nudge_x = -50
  )
```
```{r}
library(ggplot2)

qplot(x = conc, y = uptake, data=CO2, color = Type, fill = Type, 
      xlim = c(110, 500), 
      ylim = c(10, 30)) +
  geom_line(alpha = 0.5) +
  geom_path(color = "green") +
  labs(
    title = "Поглощение диоксида углерода травянистыми растениями",
    caption = "Данные",
    x = "Концентрация CO2 в окружающей среде (мл/л)",
    y = "Скорость поглощения CO2 (ммоль/м^2 сек)",
    colour = "Origin",
    tag = "Второй",
  )
```
